version: '3'
services:
  # Simplifies connecting to the host running docker. Useful for xdebug for example
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=9000
    networks:
      - my-network-name
  redis:
    image: redis:5.0-alpine
    networks:
      - my-network-name
  postgres:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=laravel
      - POSTGRES_DB=laravel
    ports:
      - 5432:5432
    volumes: 
      - ~/.pgdata:/var/lib/postgresql/data:delegated
      # - ./data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network-name
  nginx:
    # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-dev.html
    # image: webdevops/php-nginx-dev:7.2
    dns: 172.17.0.1
    build: .
    environment:
      - WEB_ALIAS_DOMAIN=*.*
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DEBUGGER=xdebug
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG="client_host=docker-host
      # ip addr show docker0 | grep -Po 'inet \K[\d.]+'
      # - XDEBUG_REMOTE_HOST=172.17.0.1
      - SSH_AUTH_SOCK=/ssh-agent
    volumes: 
      - ./:/app:delegated
      - ./docker/ssl:/opt/docker/etc/nginx/ssl:delegated
      - ${SSH_AUTH_SOCK}:/ssh-agent
    command: sh -c "/app/init.sh; supervisord"
    working_dir: /app
    ports:
     - "443:443"
    # expose:
    #  - "443"
    networks:
    - my-network-name

networks:
  my-network-name:

