apiVersion: v1
kind: PersistentVolume
metadata:
  name: idaas-claim0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  hostPath:
    path: /var/www/html
